#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
    ANSI_CONTROL_CODE="\033"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    ANSI_CONTROL_CODE="\e"
else
    echo "Unsupported OS: $OSTYPE"
fi

ANSI_FG_RED="${ANSI_CONTROL_CODE}[31m"
ANSI_FG_GREEN="${ANSI_CONTROL_CODE}[32m"
ANSI_FG_YELLOW="${ANSI_CONTROL_CODE}[33m"
ANSI_FG_BLUE="${ANSI_CONTROL_CODE}[034m"
ANSI_FG_PURPLE="${ANSI_CONTROL_CODE}[35m"
ANSI_FG_CYAN="${ANSI_CONTROL_CODE}[36m"
ANSI_FG_WHITE="${ANSI_CONTROL_CODE}[97m"

ANSI_BG_RED="${ANSI_CONTROL_CODE}[41m"
ANSI_BG_GREEN="${ANSI_CONTROL_CODE}[42m"
ANSI_BG_BLUE="${ANSI_CONTROL_CODE}[44m"
ANSI_BG_PURPLE="${ANSI_CONTROL_CODE}[45m"
ANSI_OFF="${ANSI_CONTROL_CODE}[0m"